version: '3'
services:
  web_service:
    image: 'web_image:debug'
    build:
      context: .
      dockerfile: ./src/WebApiTemplate.Web/Dockerfile.debug
    volumes:
      - '.:/code'
      - /code/src/WebApiTemplate.Application/obj
      - /code/src/WebApiTemplate.Application/bin
      - /code/src/WebApiTemplate.Core/obj
      - /code/src/WebApiTemplate.Core/bin
      - /code/src/WebApiTemplate.EntityFrameworkCore/obj
      - /code/src/WebApiTemplate.EntityFrameworkCore/bin
      - /code/src/WebApiTemplate.Web/obj
      - /code/src/WebApiTemplate.Web/bin
      - /code/test/WebApiTemplate.Tests/obj
      - /code/test/WebApiTemplate.Tests/bin
      - /code/test/WebApiTemplate.Web.Tests/obj
      - /code/test/WebApiTemplate.Web.Tests/bin
      - '~/.nuget:/root/.nuget'
      - /root/.nuget/packages/.tools      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
