version: '3'
services:
  web_service:
    image: 'web_image:staging'
    build:
      context: .
      dockerfile: ./src/WebApiTemplate.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

