version: '3'
services:
  postgresql-database:
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - 'tenants-database:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: D3s4rr0ll0
  webapi_service:
    image: 'webapi_image:latest'
    ports:
      - '80:80'
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgresql-database
networks:
  backend: null
volumes:
  tenants-database: null
