FROM microsoft/aspnetcore-build:2
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80
VOLUME /app
WORKDIR /app/src/WebApiTemplate.WebApi
ENTRYPOINT dotnet restore \
  && dotnet watch run --environment=Development