FROM microsoft/aspnetcore-build:2.0
ENV NUGET_XMLDOC_MODE skip
EXPOSE 80
RUN apt-get update && apt-get install -y unzip
WORKDIR /vsdbg
RUN apt-get update \
  && rm -rf /var/lib/apt/lists/* \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg
VOLUME /code
WORKDIR /code/src/WebApiTemplate.WebApi
ENTRYPOINT echo "Building project..." && dotnet build \
        && echo "Ready for debugging." && sleep infinity
